- name: Deploy FastAPI App
  hosts: web
  become: yes

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Pull Docker image
      command: docker pull ciarancarden/fastapi-app:{{ image_tag }}

    - name: Run container
      command: docker run -d -p 80:8000 ciarancarden/fastapi-app:{{ image_tag }}
